version: 1.0.{build}
build:
  verbosity: minimal

image: Visual Studio 2017

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: Win32

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - 'C:\Tools\vcpkg\installed'
  - 'C:\Tools\vcpkg\packages'

build_script:
  # Now initialize the submodules 
  - git submodule update --init
  
  - ps: |
      cd C:\Tools\vcpkg
      git pull -q
      git clean -dfx
      .\bootstrap-vcpkg.bat
      cd $env:APPVEYOR_BUILD_FOLDER

  - ps: |
      vcpkg remove --outdated --recurse
      If ($env:PLATFORM -eq "x64") {
          vcpkg install arb:x64-windows-static
      } Else {
          vcpkg install arb:x86-windows-static
      }

  # - ps: ls -r "C:\Tools\vcpkg\packages" | Out-File directories.txt
  # - ps: ls -r "C:\Tools\vcpkg\installed" | Out-File installed-directories.txt
  # - ps: appveyor PushArtifact (Get-Item -Path ".\directories.txt" -Verbose).FullName
  # - ps: appveyor PushArtifact (Get-Item -Path ".\installed-directories.txt" -Verbose).FullName
  
  # Now build the project
  - ps: |
      cd python-flint
      
      # Replace the "setup.py" with a patched version
      rm setup.py
      cp ..\project_setup.py .\setup.py
      
      If ($env:PLATFORM -eq "x64") {
          $PYTHONS = @(
              ("C:\\Python35-x64"),
              ("C:\\Python36-x64")
          )
          
          $VCPKG_INCLUDE_DIR = "C:\\Tools\\vcpkg\\installed\\x64-windows-static\\include"
          $VCPKG_LIBRARY_DIR = "C:\\Tools\\vcpkg\\installed\\x64-windows-static\\lib"
      } Else {
          $PYTHONS = @(
              ("C:\\Python35"),
              ("C:\\Python36")
          )
          
          $VCPKG_INCLUDE_DIR = "C:\\Tools\\vcpkg\\installed\\x86-windows-static\\include"
          $VCPKG_LIBRARY_DIR = "C:\\Tools\\vcpkg\\installed\\x86-windows-static\\lib"
      }

      $VCPKG_LIBRARY_DIR = "$VCPKG_LIBRARY_DIR;$VCPKG_LIBRARY_DIR\\manual-link"
      mkdir dist      
      foreach ($PYTHON in $PYTHONS) {
          $env:PATH="$PYTHON;$PYTHON\Scripts;$env:PATH"

          python -m pip install -U pip setuptools wheel
          pip install cython

          python setup.py build_ext `
            "--include-dirs=$VCPKG_INCLUDE_DIR;$VCPKG_INCLUDE_DIR\\flint" `
            "--library-dirs=$VCPKG_LIBRARY_DIR"

          pip wheel . --wheel-dir=dist
          rm -r -Force build
      }

      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
      }
